BearWare/TeamTalk5

TeamTalkAndroid/res/values-tr/strings.xml

You had added a new string, I've translated it.

Turkish updated for Client Name

---

TeamTalkAndroid/res/values-tr/strings.xml
iTeamTalk/iTeamTalk/tr.lproj/Localizable.strings

I've updated Android translations, translated new iOS strings and saved as UTF-8 with non-BOM to Localizable.strings. Check anyway :)

Updated Turkish translation

---

iTeamTalk/iTeamTalk/de.lproj/Localizable.strings

Sorry for being late with updates, sometimes it is a little difficult to keep track of changes among all other commits. :)

Updated german strings

---

TeamTalkAndroid/src/main/res/values-tr/strings.xml
iTeamTalk/iTeamTalk/tr.lproj/Localizable.strings
iTeamTalk/iTeamTalk/tr.lproj/Main.strings

Hi Bjorn,
New Android strings wer translated. Also some iOS strings wer fixed.
Add this to new releases.
Thanks. :)

i18n: Updated new strings for Turkish

---

README.md
TeamTalkAndroid/src/main/res/values-tr/strings.xml
iTeamTalk/iTeamTalk/Base.lproj/Main.storyboard
iTeamTalk/iTeamTalk/tr.lproj/Localizable.strings
qtTeamTalk/languages/Turkish.ts

Hi @bear101
I've updated readme file but if you are not want to supported by an unofficial platform, please revert this commit after merging.

New updates

---

TeamTalkAndroid/src/main/res/values-tr/strings.xml
iTeamTalk/iTeamTalk/tr.lproj/Localizable.strings
iTeamTalk/iTeamTalk/tr.lproj/Main.strings
qtTeamTalk/keycompdlg.cpp
qtTeamTalk/languages/Turkish.ts
qtTeamTalk/main.cpp
qtTeamTalk/mainwindow.cpp
qtTeamTalk/weblogindlg.cpp

Please send an invitation from TestFlight

Updates from a Turkish ☺

---

Client/iTeamTalk/iTeamTalk/zh_CN.lproj/Localizable.strings
Client/iTeamTalk/iTeamTalk/zh_CN.lproj/Main.strings

This is the latest iTeamTalk v5.3.3 Simplified Chinese translation, which has been checked to request to sync to the official GitHub. Thank

Update iTeamTalk v5.3.3 Simplified Chinese translation

---

Client/TeamTalkClassic/lng_classic/Chinese_Simplified.lng

Add Translation for file uploaded/downloaded to Simplified Chinese

update TeamTalkClassic Chinese_Simplified

---

Client/TeamTalkClassic/lng_classic/Chinese_Simplified.lng

update Translation for missing items Chinese_Simplified

update Translation for missing items Chinese_Simplified

---

Client/TeamTalkAndroid/src/main/res/values-zh/strings.xml

Thank you very much for #396 .

Update Chinese translation for android

---

Client/TeamTalkClassic/lng_classic/Croatian.lng
Client/TeamTalkClassic/lng_classic/Czech.lng

Here are new translated czech and croatian files.
Czech files provided by Roberto Lombino.

Croatian and czech languages update

---

Client/TeamTalkClassic/lng_classic/Croatian.lng
Client/TeamTalkClassic/lng_classic/Czech.lng

Updated croatian and czecz translations.
For czech again thanks to Roberto Lombino.

czech and croatian translation updates

---

Client/TeamTalkAndroid/src/main/res/values-tr/strings.xml
Client/iTeamTalk/iTeamTalk/tr.lproj/Localizable.strings
Client/iTeamTalk/iTeamTalk/tr.lproj/Main.strings
Client/qtTeamTalk/languages/Turkish.ts

Hi Bjoern,
I'm sorry for being late. I wish you peace.

Turkish Update

---

Client/TeamTalkClassic/lng_classic/Chinese_Simplified.lng

Update TeamTalkClassic simplified Chinese translation

---

Client/TeamTalkAndroid/build.gradle
Client/TeamTalkAndroid/src/main/AndroidManifest.xml
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/AudioCodecActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/ChannelPropActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/FilePickerActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/PreferencesActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/ServerEntryActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/ServerListActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/StreamMediaActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/TextMessageActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/UserPropActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/Utils.java
Client/TeamTalkAndroid/src/main/res/layout/activity_file_picker.xml
Client/TeamTalkAndroid/src/main/res/layout/activity_server_list.xml
Client/TeamTalkAndroid/src/main/res/menu/channel_prop.xml
Client/TeamTalkAndroid/src/main/res/menu/main.xml
Client/TeamTalkAndroid/src/main/res/menu/server_entry.xml
Client/TeamTalkAndroid/src/main/res/menu/server_list.xml

This should solve the problem stated in #477.

Android AppCompat themes usage

---

ChangeLog.txt
Client/TeamTalkAndroid/src/main/AndroidManifest.xml
Client/TeamTalkAndroid/src/main/java/dk/bearware/backend/BluetoothHeadsetHelper.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/backend/TeamTalkService.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/data/Permissions.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/data/Preferences.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java
Client/TeamTalkAndroid/src/main/res/values-ru/strings.xml
Client/TeamTalkAndroid/src/main/res/values/strings.xml
Client/TeamTalkAndroid/src/main/res/xml/pref_soundsystem.xml

It can be enabled in sound settings menu now.

Android client: bluetooth headset microphone usage facility

---

Client/qtTeamTalk/mainwindow.ui

Also add accessible names on areas of this tabs

QT - Readonly history on video and desktops tabs

---

Client/TeamTalkClassic/TeamTalk.rc
Client/TeamTalkClassic/lng_classic/Arabic.lng
Client/TeamTalkClassic/lng_classic/Chinese_Simplified.lng
Client/TeamTalkClassic/lng_classic/Croatian.lng
Client/TeamTalkClassic/lng_classic/Czech.lng
Client/TeamTalkClassic/lng_classic/Danish.lng
Client/TeamTalkClassic/lng_classic/English.lng
Client/TeamTalkClassic/lng_classic/Estonian.lng
Client/TeamTalkClassic/lng_classic/French.lng
Client/TeamTalkClassic/lng_classic/German.lng
Client/TeamTalkClassic/lng_classic/Hungarian.lng
Client/TeamTalkClassic/lng_classic/Indonesian.lng
Client/TeamTalkClassic/lng_classic/Korean.lng
Client/TeamTalkClassic/lng_classic/Polish.lng
Client/TeamTalkClassic/lng_classic/Portuguese_BR.lng
Client/TeamTalkClassic/lng_classic/Russian.lng
Client/TeamTalkClassic/lng_classic/Spanish.lng
Client/TeamTalkClassic/lng_classic/Turkish.lng

This informations are osboletes, volume are changing one by one, not 10 by 10.

Remove +10 and -10 from volumes menus

---

Client/TeamTalkClassic/lng_classic/Chinese_Simplified.lng

Follow up #672 
Complete translation-pull-672
thanks

Update Chinese_Simplified TeamTalkClassic

---

Client/TeamTalkClassic/lng_classic/Croatian.lng
Client/TeamTalkClassic/lng_classic/Polish.lng

Updated polish and croatian translations. 
Note: to derive the context of the strings and improve the translation, i will need the beta, or know a way how to compile the beta locally.

Updated polish and croatian translations

---

Client/TeamTalkClassic/lng_classic/Croatian.lng
Client/TeamTalkClassic/lng_classic/Polish.lng

next update,
features are interesting...

updated polish and croatian translation

---

Client/TeamTalkClassic/lng_classic/Croatian.lng
Client/TeamTalkClassic/lng_classic/Polish.lng

Just two new strings updated which were added in the last commits.

small polish and croatian update

---

Client/TeamTalkClassic/lng_classic/Polish.lng

* small fixes to the translation, especially fixed some typos
* updated the contributor of the translation, along with his contact info, so that community members can contact him.

Small fixes to the polish translation

---

Client/TeamTalkClassic/lng_classic/Croatian.lng
Client/TeamTalkClassic/lng_classic/Polish.lng

Small update with the sound events on the corresponding settings pages.

Updated croatian and polish

---

ChangeLog.txt
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/FilePickerActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/ServerListActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/Utils.java
Client/TeamTalkAndroid/src/main/res/menu/server_list.xml
Client/TeamTalkAndroid/src/main/res/values-ru/strings.xml
Client/TeamTalkAndroid/src/main/res/values/strings.xml

AFAIK, it is just the feature in demand. Please consider it for the
upcoming release.

Server list export facility in Android client

---

Client/TeamTalkClassic/TeamTalk.rc
Client/TeamTalkClassic/TeamTalkDlg.cpp
Client/TeamTalkClassic/gui/WindowPage.cpp
Client/TeamTalkClassic/gui/WindowPage.h
Client/TeamTalkClassic/lng_classic/English.lng
Client/TeamTalkClassic/lng_classic/French.lng
Client/TeamTalkClassic/resource.h
Client/TeamTalkClassic/settings/ClientXML.cpp
Client/TeamTalkClassic/settings/ClientXML.h
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/preferences.ui
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/preferencesdlg.h
Client/qtTeamTalk/settings.h

Sorry for GUI probably broken, I'll request someone to check this.

Option to disable user logs in/out display in chat history

---

Client/iTeamTalk/iTeamTalk/tr.lproj/Localizable.strings

iTeamTalk: Update Turkish translation

---

Client/TeamTalkClassic/lng_classic/Croatian.lng
Client/TeamTalkClassic/lng_classic/Polish.lng

latest strings updated successfullz.

updated translations: polish and croatian

---

Client/TeamTalkAndroid/src/main/res/values-uk/strings.xml

This is updated Ukrainian translations, translated new lines

Updated Ukrainian translations

---

Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/settings.h
Setup/Client/Linux/TeamTalk5.ini
Setup/Client/Mac/TeamTalk5.ini
Setup/Client/Windows/TeamTalk5.ini

- To make transition bitween classic and QT client more agreable :)

Windows - Propose to enable TTS if screenreader is detected at first QT startup

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/preferences.ui
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/preferencesdlg.h
Client/qtTeamTalk/settings.h

I hope we have place for this new option. Not checked for now...

QT - Option to display update availability in a dialog instead of chat history

---

ChangeLog.txt
Client/qtTeamTalk/common.h
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/ttseventsmodel.cpp

- Add event when savingserver configuration (tts_menu_actions)
- Add new events for server connectivity (connect/disconnect/lost connection)

QT - Add more TTS events

---

Library/TeamTalkLib/avstream/MFStreamer.cpp

If audio input format is a compressed format (e.g. mp3) then we must
specify audio output format. Otherwise we'll output the compressed
data thinking it's PCM16.

Only disregard MFStreamer's audio output format if PCM16 wave-file.

---

Client/qtTeamTalk/mainwindow.ui

Requested by users, "Download" button should appear before "Upload"

QT - Change buttons order in files tab

---

ChangeLog.txt
Client/iTeamTalk/iTeamTalk/MainTabBarController.swift
Client/iTeamTalk/iTeamTalk/ServerDetailViewController.swift
Client/iTeamTalk/iTeamTalk/ServerListViewController.swift

I hope nothing more is required. Unfortunately I can't test...

iOS - Ability to specify nickname by server

---

Client/TeamTalkClassic/lng_classic/Croatian.lng
Client/TeamTalkClassic/lng_classic/Polish.lng

Polish and croatian languages updated accordingly.

Updated translations for the classic client

---

Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h
Client/qtTeamTalk/mainwindow.ui

@bear101 Should I also add an action to upload a file in this context menu?

Qt - Add a context menu on files list

---

Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h
Client/qtTeamTalk/mainwindow.ui

Without change log entry for now because we probably have to wait until the next version due to beta currently public.

Qt - Implement CTRL+Shift+G to speak channel state

---

Client/qtTeamTalk/CMakeLists.txt
Client/qtTeamTalk/mainwindow.pri
Client/qtTeamTalk/mycombobox.cpp
Client/qtTeamTalk/mycombobox.h
Client/qtTeamTalk/serverlist.ui
Client/qtTeamTalk/streammediafile.ui
Client/qtTeamTalk/streammediafiledlg.cpp

@Oreonan Does this fix the Enter key issue in ServerListDlg and StreamMediaFileDlg? This is related to #1010
If it does then I can also change the other QComboBox classes

Process Enter-key when QComboBox has focus

---

Setup/Server/Linux/init.d/tt5proserver
Setup/Server/Linux/init.d/tt5server
Setup/Server/Linux/systemd/tt5proserver.service
Setup/Server/Linux/systemd/tt5server.service

* Add reload and force-reload parameters to init scripts
* Add ExecReload to systemd unit files

Implement reload action for init and systemd

---

ChangeLog.txt
Client/TeamTalkAndroid/src/main/java/dk/bearware/backend/TeamTalkService.java

Supposed to fix #913 but there is maybe a better way to do that. Still not really good with development for Android

Android - Join specified channel from user account

---

Client/iTeamTalk/iTeamTalk.xcodeproj/project.pbxproj
Client/iTeamTalk/iTeamTalk/Base.lproj/Main.storyboard
Client/iTeamTalk/iTeamTalk/Common.swift
Client/iTeamTalk/iTeamTalk/PreferencesViewController.swift
Client/iTeamTalk/iTeamTalk/SoundInputsViewController.swift
Client/iTeamTalk/iTeamTalkTests/iTeamTalkTests.swift

View controller for selecting microphone input. Makes stereo selection possible for #546

Microphone selection for iOS

---

Client/qtTeamTalk/common.cpp
Client/qtTeamTalk/common.h
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h
Client/qtTeamTalk/mainwindow.ui
Client/qtTeamTalk/onlineusersdlg.cpp
Client/qtTeamTalk/preferences.ui
Client/qtTeamTalk/userdesktopwidget.cpp

Quick access to change sound devices

Select sound devices from Client menu

---

Library/TeamTalkLib/myace/MyACE.cpp
Library/TeamTalkLib/myace/MyACE.h
Library/TeamTalkLib/teamtalk/Commands.cpp
Library/TeamTalkLib/test/CatchDefault.cpp

Also fixes problem where exceeded string became blank

Cut UTF-8 strings in place where remaining string is still valid

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/textmessage.ui
Client/qtTeamTalk/textmessagedlg.cpp

@bear101 If you are agree with this approach, I can also modify in main window. The GUI has probably to be reviewed also.
@beqabeqa473 Is this approach better for you?

Change way to display number of characters for messages

---

Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h

Generalize getTitle function and use it also for TrayIcon

---

Library/TeamTalkLib/teamtalk/client/ClientNode.cpp

This also fixes an issue were no keepalive is sent immediately after
lowering the user-time. E.g. changing from 60 -> 5 sec would not
trigger a keepalive until after 2.5 sec.

Ensure keepalive is sent when server properties' user-timeout is changed

---

Client/TeamTalkAndroid/build.gradle
Client/TeamTalkAndroid/src/main/AndroidManifest.xml
Client/TeamTalkAndroid/src/main/java/dk/bearware/backend/TeamTalkService.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java

fixes problem for android 12 #1199

Android: another way of processing mediaButton events.

---

Library/TeamTalkLib/build/ace/CMakeLists.txt
Library/TeamTalkLib/build/portaudio/CMakeLists.txt

Also align ACE with other ExternalProject's TOOLCHAIN_BUILD_PREFIX

Set TOOLCHAIN_BUILD_PREFIX on PortAudio

---

Library/TeamTalkJNI/test/dk/bearware/TeamTalkTestCase.java
Library/TeamTalkLib/bin/dll/TTClientMsg.cpp

Set queue size to a full server with max users and max channels. This
should fix issue #1212.

Increase event queue size so it can handle initial login

---

Client/qtTeamTalk/channel.ui
Client/qtTeamTalk/channeldlg.cpp
Client/qtTeamTalk/channeldlg.h
Library/TeamTalk.NET/TeamTalk.cs
Library/TeamTalkJNI/jni/ttconvert-jni.cpp
Library/TeamTalkJNI/src/dk/bearware/Channel.java
Library/TeamTalkJNI/test/dk/bearware/TeamTalkTestCase.java
Library/TeamTalkLib/bin/dll/Convert.cpp
Library/TeamTalkLib/teamtalk/Channel.h
Library/TeamTalkLib/teamtalk/Commands.h
Library/TeamTalkLib/teamtalk/Common.h
Library/TeamTalkLib/teamtalk/client/ClientNode.cpp
Library/TeamTalkLib/teamtalk/server/ServerChannel.cpp
Library/TeamTalkLib/teamtalk/server/ServerChannel.h
Library/TeamTalkLib/teamtalk/server/ServerNode.cpp
Library/TeamTalkLib/teamtalk/server/ServerUser.cpp
Library/TeamTalk_DLL/TeamTalk.h

Configurable delay on transmit queue

---

ChangeLog.txt
Client/TeamTalkClassic/Helper.cpp
Client/TeamTalkClassic/Helper.h
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/utilsound.cpp
Client/qtTeamTalk/utilsound.h
Library/TeamTalkLib/build/portaudio/CMakeLists.txt

Ability to use WASAPI to use loopback sound device

---

Client/qtTeamTalk/languages/Russian.ts

Hello. During beta testing, I found an error in translation. I apologize for the frequent requests, but I am interested in making the translation work correctly. Thanks.

Fixing the Russian translation in the file transfer window

---

ChangeLog.txt
Client/qtTeamTalk/chattextedit.cpp
Client/qtTeamTalk/chattextedit.h
Client/qtTeamTalk/common.h
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/textmessagedlg.cpp
Client/qtTeamTalk/userdesktopwidget.cpp
Client/qtTeamTalk/utilui.cpp
Client/qtTeamTalk/utilui.h
Library/TeamTalkJNI/jni/ttconvert-jni.cpp
Library/TeamTalkJNI/src/dk/bearware/TextMessage.java
Library/TeamTalkJNI/test/dk/bearware/TeamTalkServerTestCase.java
Library/TeamTalkLib/bin/dll/Convert.cpp
Library/TeamTalkLib/teamtalk/Commands.h
Library/TeamTalkLib/teamtalk/Common.h
Library/TeamTalkLib/teamtalk/client/ClientNode.cpp
Library/TeamTalkLib/teamtalk/server/ServerUser.cpp
Library/TeamTalk_DLL/TeamTalk.h

Fixes #1236 in qtTeamTalk.
Merge if it looks ok. Remember to build a new server as well since the TCP protocol is changed.

Longer text messages in qtTeamTalk

---

Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h
Client/qtTeamTalk/mainwindow.ui
Client/qtTeamTalk/ttseventsmodel.cpp
Client/qtTeamTalk/utiltts.h

Menu shortcut to question mode and TTS event

---

Client/qtTeamTalk/languages/Russian.ts

Updating Russian translation

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h
Client/qtTeamTalk/mainwindow.ui

@bear101 this is for issue #1250. Maybe you'll have a better idea for shortcut and placement for menu item?

Option to speak client statistics

---

Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h
Client/qtTeamTalk/mainwindow.ui

@CoBC shouldn't it be possible to generate a tt-URL to any channel on a server?
At the moment it's a bit confusing that the menu item says "This Channel" when another channel is currently selected.

Sharing TT URLs

---

Client/qtTeamTalk/serverlogeventsmodel.cpp
Client/qtTeamTalk/serverlogeventsmodel.h
Client/qtTeamTalk/statusbareventsmodel.cpp
Client/qtTeamTalk/statusbareventsmodel.h
Client/qtTeamTalk/ttseventsmodel.cpp
Client/qtTeamTalk/ttseventsmodel.h

@bear101 I've let the AccessibleTextRole on Qt5 because CheckState is only accessible in Qt6.

CheckState on models

---

Client/qtTeamTalk/CMakeLists.txt
Client/qtTeamTalk/chattextedit.cpp
Client/qtTeamTalk/chattextedit.h
Client/qtTeamTalk/common.cpp
Client/qtTeamTalk/common.h
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h
Client/qtTeamTalk/mainwindow.pri
Client/qtTeamTalk/settings.h
Client/qtTeamTalk/textmessagecontainer.cpp
Client/qtTeamTalk/textmessagecontainer.h
Client/qtTeamTalk/textmessagedlg.cpp
Library/TeamTalk_DLL/TeamTalk.h

Separate text message container that merges text messages prior to passing them on.

Text message container that handles merge-messages

---

Client/qtTeamTalk/textmessagecontainer.cpp

This solves missing private text messages from "myself".
Fixes #1381

Pass private text message from 'myself' into 'nToUserID' text message container

---

Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h

Do not enable voice activation after returning from idle timeout

---

Client/qtTeamTalk/mainwindow.cpp

Prevent double initial message in text message dialog

---

ChangeLog.txt
Client/qtTeamTalk/preferences.ui
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/settings.h
Client/qtTeamTalk/utilsound.cpp

Option to configure sound events volume - Fixed #1393)

---

Client/qtTeamTalk/languages/Spanish.ts

Hello,
I send an update of the Spanish translation of the windows client, since in my opinion it was quite incomplete.
Although it is not a professional translation by any means, I plan to improve it periodically as new strings are added or errors are detected or reported.

Update spanish translation

---

ChangeLog.txt
Library/TeamTalkLib/bin/dll/ServerMonitor.cpp
Library/TeamTalkLib/bin/dll/ServerMonitor.h
Library/TeamTalkLib/bin/ttsrv/ServerGuard.cpp
Library/TeamTalkLib/bin/ttsrv/ServerGuard.h
Library/TeamTalkLib/teamtalk/server/ServerNode.cpp
Library/TeamTalkLib/teamtalk/server/ServerNode.h

Log subscription changes on server

---

ChangeLog.txt
Library/TeamTalkJNI/test/dk/bearware/TeamTalkServerTestCase.java
Library/TeamTalkLib/teamtalk/server/ServerUser.cpp

Forward password and operator password of auto operator channels

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/preferences.ui
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/preferencesdlg.h
Client/qtTeamTalk/settings.h

@bear101 I tried to refresh available voices when changing language in combobox, but it crashed. Can you try to do this part?

Option to configure Qt TTS language

---

Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h

Announce toggled class room changes

---

Client/qtTeamTalk/languages/Bulgarian.ts
Client/qtTeamTalk/languages/Chinese_Simplified.ts
Client/qtTeamTalk/languages/Chinese_Traditional.ts
Client/qtTeamTalk/languages/Croatian.ts
Client/qtTeamTalk/languages/Czech.ts
Client/qtTeamTalk/languages/Danish.ts
Client/qtTeamTalk/languages/Dutch.ts
Client/qtTeamTalk/languages/English.ts
Client/qtTeamTalk/languages/French.ts
Client/qtTeamTalk/languages/German.ts
Client/qtTeamTalk/languages/Hebrew.ts
Client/qtTeamTalk/languages/Hungarian.ts
Client/qtTeamTalk/languages/Indonesian.ts
Client/qtTeamTalk/languages/Italian.ts
Client/qtTeamTalk/languages/Polish.ts
Client/qtTeamTalk/languages/Portuguese_BR.ts
Client/qtTeamTalk/languages/Portuguese_EU.ts
Client/qtTeamTalk/languages/Russian.ts
Client/qtTeamTalk/languages/Slovak.ts
Client/qtTeamTalk/languages/Slovenian.ts
Client/qtTeamTalk/languages/Spanish.ts
Client/qtTeamTalk/languages/Thai.ts
Client/qtTeamTalk/languages/Turkish.ts
Client/qtTeamTalk/mainwindow.cpp

It is required for some languages (included French) to have diferent strings for diferent contexts. So I introduced this changes here.

Improve translations for classroom changes

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp

New profile for settings starts from blank ini-file

---

Client/ttsamplepy/ttsample.py
Library/TeamTalkPy/TeamTalk5.py

This pr adds event handling possibility to be used by client developers in python.

Event handling in python wrapper

---

Library/TeamTalkLib/bin/ttsrv/ServerXML.cpp
Library/TeamTalkLib/myace/MyACE.cpp
Library/TeamTalkLib/test/CatchDefault.cpp

Fix incorrect Modified date on user accounts

---

Client/qtTeamTalk/mainwindow.cpp

Reset channel passwords and user account after disconnecting manually

---

ChangeLog.txt
Client/qtTeamTalk/languages/Bulgarian.ts
Client/qtTeamTalk/languages/Chinese_Simplified.ts
Client/qtTeamTalk/languages/Chinese_Traditional.ts
Client/qtTeamTalk/languages/Croatian.ts
Client/qtTeamTalk/languages/Czech.ts
Client/qtTeamTalk/languages/Danish.ts
Client/qtTeamTalk/languages/Dutch.ts
Client/qtTeamTalk/languages/English.ts
Client/qtTeamTalk/languages/French.ts
Client/qtTeamTalk/languages/German.ts
Client/qtTeamTalk/languages/Hebrew.ts
Client/qtTeamTalk/languages/Hungarian.ts
Client/qtTeamTalk/languages/Indonesian.ts
Client/qtTeamTalk/languages/Italian.ts
Client/qtTeamTalk/languages/Polish.ts
Client/qtTeamTalk/languages/Portuguese_BR.ts
Client/qtTeamTalk/languages/Portuguese_EU.ts
Client/qtTeamTalk/languages/Russian.ts
Client/qtTeamTalk/languages/Slovak.ts
Client/qtTeamTalk/languages/Slovenian.ts
Client/qtTeamTalk/languages/Spanish.ts
Client/qtTeamTalk/languages/Thai.ts
Client/qtTeamTalk/languages/Turkish.ts
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/preferences.ui
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/settings.h
Client/qtTeamTalk/utilsound.cpp
Client/qtTeamTalk/utilsound.h

Three options to play sound events:
1. Use default OS playback
2. Use TeamTalk sound devices doing one-by-one playback
3. Use TeamTalk sound devices doing overlapping playback

Playback sound events using TT_InitLocalPlayback

---

Client/qtTeamTalk/mainwindow.cpp

This should fixe the issue discussed in #1575

Disable upload action when not connected

---

Client/iTeamTalk/iTeamTalk/id.lproj/Localizable.strings

I changed some translations, now so much better.

update Indonesian iOS translation

---

ChangeLog.txt
Client/qtTeamTalk/chattextedit.cpp
Client/qtTeamTalk/chattextedit.h
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/textmessagecontainer.cpp
Client/qtTeamTalk/textmessagecontainer.h
Client/qtTeamTalk/textmessagedlg.cpp
Client/qtTeamTalk/textmessagedlg.h

Clear text message history

---

ChangeLog.txt
Library/TeamTalkJNI/test/dk/bearware/TeamTalkTestCase.java
Library/TeamTalkLib/teamtalk/server/ServerNode.cpp

Check if channel exists on user prior to getting channel path

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.ui

Not sure why it ended up in "Input Devices" submenu in the first place...

Move "Refresh Sound Devices" to "Sound Configuration" menu

---

ChangeLog.txt
Client/qtTeamTalk/filetransfer.ui

Fix keyboard navigation on "File transfer" dialog

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp

Enabled upload action following user right

---

Client/qtTeamTalk/channel.ui
Client/qtTeamTalk/channeldlg.cpp
Client/qtTeamTalk/serverproperties.ui
Client/qtTeamTalk/serverpropertiesdlg.cpp

Applies to 'Server Properties' and 'Channel' dialog

Ability to copy text from channel path and MOTD variables

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h
Library/TeamTalkLib/bin/dll/TTClientMsg.cpp
Library/TeamTalkLib/bin/dll/TTClientMsg.h
Library/TeamTalkLib/bin/dll/TeamTalk.cpp
Library/TeamTalkLib/build/ttclient.cmake
Library/TeamTalkLib/win32/AudioDeviceNotify.cpp
Library/TeamTalkLib/win32/AudioDeviceNotify.h
Library/TeamTalk_DLL/TeamTalk.h

Notification when sound device is added/removed

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/ttseventsmodel.cpp
Client/qtTeamTalk/utiltts.h

TTS event on video transmission toggled

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/ttseventsmodel.cpp
Client/qtTeamTalk/utiltts.h

Also requested in comments of #1666

TTS event for desktop sharing toggled

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp

Add server name in TTS event when disconnecting

---

ChangeLog.txt
Client/qtTeamTalk/filesmodel.cpp

add g size in list file

---

Library/TeamTalkLib/bin/dll/TTClientMsg.cpp
Library/TeamTalkLib/bin/dll/TTClientMsg.h
Library/TeamTalkLib/teamtalk/Commands.cpp
Library/TeamTalkLib/teamtalk/Commands.h
Library/TeamTalkLib/teamtalk/client/ClientNode.cpp
Library/TeamTalkLib/teamtalk/client/ClientNode.h
Library/TeamTalkLib/teamtalk/client/ClientNodeEvent.h
Library/TeamTalkLib/teamtalk/server/ServerNode.cpp
Library/TeamTalkLib/teamtalk/server/ServerUser.cpp
Library/TeamTalkLib/teamtalk/server/ServerUser.h
Library/TeamTalk_DLL/TeamTalk.h

Add events for adding/deleting user accounts

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp

Ask for operator password when USERRIGHT_OPERATOR_ENABLE is not set

---

ChangeLog.txt
Client/qtTeamTalk/serverproperties.ui
Client/qtTeamTalk/serverpropertiesdlg.cpp

Check "Show MOTD variables" checkbox by default

---

Client/qtTeamTalk/preferencesdlg.cpp

Set focus to nicknameEdit when opening preferences dialog

---

Library/TeamTalkPy/TeamTalk5.py

Type info on arguments and return values.
Align names of arguments with Java TeamTalk API.

Additional TeamTalk API functions for TeamTalkPy

---

Client/qtTeamTalk/onlineusersdlg.cpp
Client/qtTeamTalk/settings.h

Currently only Id and Nickname sort is available. @bear101 should I add more sorting options?

Ability to sort online users list

---

Library/TeamTalkPy/TeamTalk5.py

Add the ability to kick user using TeamTalkPy

Add doKickUser to TeamTalkPy

---

Library/TeamTalkPy/TeamTalk5.py

Add doRemoveChannel Python class method.

Implement doRemoveChannel on TeamTalkPy

---

ChangeLog.txt
Client/qtTeamTalk/serverlist.ui
Client/qtTeamTalk/serverlistdlg.cpp
Client/qtTeamTalk/serverlistdlg.h
Client/qtTeamTalk/settings.h

Unofficial server list is long, so it's nice to filter out servers with 0 users.

Filter server list based on server type, name and number of users

---

Library/TeamTalkLib/build/libvpx/CMakeLists.txt
Library/TeamTalkLib/build/libvpx/build-libvpx-win.bat_sample

Try looking for MSYS2 as well as Cygwin in search of bash.exe

---

Client/qtTeamTalk/CMakeLists.txt
Client/qtTeamTalk/aboutdlg.cpp
Client/qtTeamTalk/appinfo.h
Client/qtTeamTalk/bearwarelogindlg.cpp
Client/qtTeamTalk/common.cpp
Client/qtTeamTalk/common.h
Client/qtTeamTalk/generatettfiledlg.cpp
Client/qtTeamTalk/keycompdlg.cpp
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h
Client/qtTeamTalk/mainwindow.pri
Client/qtTeamTalk/serverlistdlg.cpp
Client/qtTeamTalk/userdesktopwidget.cpp
Client/qtTeamTalk/utilhotkey.cpp
Client/qtTeamTalk/utilos.cpp
Client/qtTeamTalk/utilos.h
Client/qtTeamTalk/utiltt.cpp
Client/qtTeamTalk/utiltt.h
Client/qtTeamTalk/utilxml.cpp
Client/qtTeamTalk/utilxml.h

This merge request moves TT, XML and OS related functions into their respective util-files.

Reduce size of common.h/cpp

---

Client/TeamTalkAndroid/src/main/java/dk/bearware/data/AppInfo.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/data/Preferences.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/ServerListActivity.java
Client/TeamTalkAndroid/src/main/res/xml/pref_serverlist.xml
Client/iTeamTalk/iTeamTalk/AppInfo.swift
Client/iTeamTalk/iTeamTalk/Base.lproj/Main.storyboard
Client/iTeamTalk/iTeamTalk/PublicServerViewController.swift
Client/iTeamTalk/iTeamTalk/ServerListViewController.swift
Client/iTeamTalk/iTeamTalk/ar.lproj/Main.strings
Client/iTeamTalk/iTeamTalk/da.lproj/Main.strings
Client/iTeamTalk/iTeamTalk/de.lproj/Main.strings
Client/iTeamTalk/iTeamTalk/en.lproj/Main.strings
Client/iTeamTalk/iTeamTalk/es.lproj/Main.strings
Client/iTeamTalk/iTeamTalk/fr.lproj/Main.strings
Client/iTeamTalk/iTeamTalk/hu.lproj/Main.strings
Client/iTeamTalk/iTeamTalk/id.lproj/Main.strings
Client/iTeamTalk/iTeamTalk/it.lproj/Main.strings
Client/iTeamTalk/iTeamTalk/ko.lproj/Main.strings
Client/iTeamTalk/iTeamTalk/ms.lproj/Main.strings
Client/iTeamTalk/iTeamTalk/nl.lproj/Main.strings
Client/iTeamTalk/iTeamTalk/pl.lproj/Main.strings
Client/iTeamTalk/iTeamTalk/pt-BR.lproj/Main.strings
Client/iTeamTalk/iTeamTalk/ru.lproj/Main.strings
Client/iTeamTalk/iTeamTalk/tr.lproj/Main.strings
Client/iTeamTalk/iTeamTalk/zh.lproj/Main.strings
Client/qtTeamTalk/appinfo.h
Client/qtTeamTalk/serverlist.ui
Client/qtTeamTalk/serverlistdlg.cpp
Client/qtTeamTalk/settings.h

For now public servers still appear because when public servers are unspecified then the web-service defaults to true.
Fixes #1872

Remove public servers

---

Client/TeamTalkAndroid/src/main/java/dk/bearware/data/TTSWrapper.java

Android client: Possible NPE fix

---

Client/qtTeamTalk/languages/Russian.ts

Hotkeys have been added to important interface elements. Improvement of the accessibility of the Russian translation.

Improvements to Russian translation

---

Library/TeamTalkLib/build/ace/0001-Make-CROSS_COMPILE-configurable-for-Android.patch
Library/TeamTalkLib/build/ace/0002-Enable-SNI-for-TLS.patch
Library/TeamTalkLib/build/ace/0003-Static-build-config-for-Windows.patch
Library/TeamTalkLib/build/ace/CMakeLists.txt
Library/TeamTalkLib/build/ffmpeg/CMakeLists.txt
Library/TeamTalkLib/build/libvpx/CMakeLists.txt
Library/TeamTalkLib/build/ogg/CMakeLists.txt
Library/TeamTalkLib/build/openssl/CMakeLists.txt
Library/TeamTalkLib/build/opustools/CMakeLists.txt
Library/TeamTalkLib/build/portaudio/CMakeLists.txt
Library/TeamTalkLib/build/speex/CMakeLists.txt
Library/TeamTalkLib/build/speexdsp/CMakeLists.txt
Library/TeamTalkLib/build/zlib/CMakeLists.txt

Patches generated on branch bdr/ACE+TAO-7_1_1

Update to ACE v7.1.1 from DOCGroup/ACE_TAO on GitHub

---

Library/TeamTalkJNI/test/dk/bearware/TeamTalkServerTestCase.java
Library/TeamTalkLib/bin/dll/ServerMonitor.cpp
Library/TeamTalkLib/bin/dll/ServerMonitor.h
Library/TeamTalkLib/bin/ttsrv/ServerGuard.cpp
Library/TeamTalkLib/bin/ttsrv/ServerGuard.h
Library/TeamTalkLib/teamtalk/server/ServerNode.cpp
Library/TeamTalkLib/teamtalk/server/ServerNode.h

Issue SERVERLOGEVENT_SERVER_UPDATED when calling TTS_UpdateServer()

---

ChangeLog.txt
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/ServerListActivity.java

Fix tt file import On android 11 and up

---

.github/workflows/android.yml

Update Android workflow to Java 17

---

ChangeLog.txt
Client/qtTeamTalk/common.cpp
Client/qtTeamTalk/mediastoragedlg.cpp
Library/TeamTalkLib/avstream/SoundSystemBase.h
Library/TeamTalkLib/bin/dll/TeamTalk.cpp
Library/TeamTalkLib/teamtalk/Common.cpp
Library/TeamTalkLib/teamtalk/Common.h
Library/TeamTalkLib/teamtalk/client/AudioMuxer.cpp
Library/TeamTalkLib/teamtalk/client/VoiceLogger.cpp
Library/TeamTalkLib/test/CatchDefault.cpp
Library/TeamTalkLib/test/CatchWin.cpp
Library/TeamTalk_DLL/TeamTalk.h

Support for 320 KBit MP3 recording on Windows

---

Client/jSpamBot/src/Main.java

Fixes:
TeamTalk 5 SpamBot for Java
Exception in thread "main" java.io.IOException: Invalid password for spambot. Error code: 508
at WebLogin.<init>(WebLogin.java:77)
at Main.main(Main.java:91)

Handle failed HTTP request on WebLogin

---

Client/jSpamBot/src/AbuseDB.java
Client/jSpamBot/src/Main.java

As Java properties to jSpamBot

Configurable AbuseDB properties

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/preferences.ui
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/settings.h

Currently only implemented for user logged in and out

Option to announce server name for some server related TTS events

---

Client/TeamTalkAndroid/src/main/AndroidManifest.xml
Client/TeamTalkAndroid/src/main/java/dk/bearware/backend/BluetoothHeadsetHelper.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/data/FileListAdapter.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/data/Permissions.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/ServerListActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/StreamMediaActivity.java
Client/TeamTalkAndroid/src/main/res/values-ru/strings.xml
Client/TeamTalkAndroid/src/main/res/values/strings.xml

General refactoring and fix-up. Implemented modern media access
permissions request.

Revised Android client permissions management infrastructure

---

Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/AbsolutePathHelper.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/ServerListActivity.java

This solution is not the perfect one, but it works. To use proper
approach some TeamTalk library functions API modifications are
necessary.
Hopefully fixes #2117

Android client: file transfer functionality fix

---

Client/TeamTalkAndroid/src/main/res/layout/item_textmsg.xml

Recognize e-mails and phone numbers along with web-addresses.

Android client: Links in messages enhancement

---

Client/TeamTalkAndroid/src/main/java/dk/bearware/backend/TeamTalkService.java

Use more advanced API where it is available.
Please, try it out. Hopefully fixes #2222 problem.

Android client foreground service fix

---

Client/qtTeamTalk/serverlistdlg.cpp

Fix clear latest hosts

---

Client/qtTeamTalk/serverlistdlg.cpp

Ensure server is selected to enabled context menu actions

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp

@bear101 We should also clear list and reset tab text

Reset files list label when disconnected from server

---

Client/qtTeamTalk/serverlistdlg.cpp

tested them and made sure there is no problem and they function properly

added connect action to the host manager's context menus

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h
Client/qtTeamTalk/mainwindow.ui

Add "Check for Update" in "Help" menu

---

ChangeLog.txt
Client/qtTeamTalk/CMakeLists.txt
Client/qtTeamTalk/channelstree.cpp
Client/qtTeamTalk/channelstree.h
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h
Client/qtTeamTalk/mainwindow.pri
Client/qtTeamTalk/mainwindow.ui
Client/qtTeamTalk/moveusersdlg.cpp
Client/qtTeamTalk/moveusersdlg.h

Fixes #1833
@bear101 Maybe you prefer to have an ui file. If yes, can you create it please? :)

Implement "Move Users" dialog

---

Client/qtTeamTalk/ttseventsmodel.cpp
Client/qtTeamTalk/utiltts.cpp
Client/qtTeamTalk/utiltts.h

@CoBC change ttseventsmodel.cpp:257

Display current message in extra column

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h

Ability to replace existing file on upload

---

ChangeLog.txt
Client/qtTeamTalk/bannedusers.ui
Client/qtTeamTalk/bannedusersdlg.cpp
Client/qtTeamTalk/bannedusersdlg.h

Don't understand why it's crashing when searching something which don't exist :(
@bear101 Do you have an idea?

Ability to search in "Banned Users"

---

Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/statusbardlg.cpp

Only check if message is different from current message, don't check default value

Fix "Reset to default value"

---

Client/qtTeamTalk/bannedusers.ui
Client/qtTeamTalk/mytableview.cpp
Client/qtTeamTalk/onlineusers.ui
Client/qtTeamTalk/useraccountdlg.ui
Client/qtTeamTalk/useraccounts.ui

Now:
- Home/End to switch to first/latest column of selected row (like previously)
- CTRL+Home/End to switch to first/latest row of selected column (instead of first row first column and latest row latest column)

Change CTRL+Home/End keys behaviour on QTableView

---

Client/qtTeamTalk/channelstree.cpp

Use the same behaviour as MOTD in server list

Move channel topic to tooltip

---

Client/qtTeamTalk/mainwindow.cpp

Also ensure login event is correctly add only if login is successful

Align status and TTS messages for server connectivity events

---

ChangeLog.txt
Client/qtTeamTalk/about.ui
Client/qtTeamTalk/filetransfer.ui
Client/qtTeamTalk/mainwindow.ui
Client/qtTeamTalk/preferences.ui
Client/qtTeamTalk/serverstats.ui
Client/qtTeamTalk/useraccountdlg.ui
Client/qtTeamTalk/userinfo.ui

- Use focusPolicy property instead of textInteractionFlags
- Allow progress bar to get focus

Improve widgets focus

---

Client/qtTeamTalk/bannedusersdlg.cpp
Client/qtTeamTalk/useraccountdlg.cpp
Client/qtTeamTalk/useraccountdlg.h
Client/qtTeamTalk/useraccountsdlg.cpp

Previously default user rights were USERRIGHT_NONE.

Set default user rights when creating new user account

---

Client/qtTeamTalk/CMakeLists.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.ui
Client/qtTeamTalk/mytabwidget.cpp
Client/qtTeamTalk/mytabwidget.h
Client/qtTeamTalk/preferences.ui
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/preferencesdlg.h
Client/qtTeamTalk/useraccountdlg.cpp
Client/qtTeamTalk/useraccountdlg.h
Client/qtTeamTalk/useraccountdlg.ui

If #2370 is accept, we'll have to replace QTabWidget by MyTabWidget also on Server dialog

Subclass QTabWidget to override keyPressEvent

---

ChangeLog.txt
Setup/Installer/Windows/TeamTalk5.iss

Just add French to see if it works. If it's OK, we can add more languages

Translate installer

---

Client/qtTeamTalk/channelstree.cpp

Also replace "question" by ❓ for question mode

Separate all emojis by comas in channel list

---

Client/TeamTalkAndroid/src/main/res/values-ko/strings.xml
Client/qtTeamTalk/languages/Korean.ts

I updated the Korean translations of TeamTalkAndroid and qtTeamTalk to be compatible with the latest version.
Thank you.

updated the Korean translations of TeamTalkAndroid and qtTeamTalk

---

ChangeLog.txt
Client/qtTeamTalk/CMakeLists.txt
Client/qtTeamTalk/appinfo.h
Client/qtTeamTalk/channelstree.cpp
Client/qtTeamTalk/generatettfiledlg.cpp
Client/qtTeamTalk/keycompdlg.cpp
Client/qtTeamTalk/keycompdlg.h
Client/qtTeamTalk/main.cpp
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h
Client/qtTeamTalk/preferences.ui
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/preferencesdlg.h
Client/qtTeamTalk/settings.h
Client/qtTeamTalk/shortcutsmodel.cpp
Client/qtTeamTalk/shortcutsmodel.h
Client/qtTeamTalk/utilhotkey.cpp
Client/qtTeamTalk/utilhotkey.h
Client/qtTeamTalk/utilui.cpp

@bear101 There is a strange issue, when double clicking on an item, keycompdlg appears and disappears immediately, if I add a QMessageBox before opening keycompdlg, all works fine.
Do you have any idea?

Switch to QTableView model-based for shortcuts tab

---

ChangeLog.txt
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/utilsound.cpp
Client/qtTeamTalk/utilsound.h

Set TeamTalk Sound Device as AudioDevice for QSoundEffect

---

Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/utiltts.cpp
Client/qtTeamTalk/utiltts.h

Add Apple Script support for TTS Events

---

Client/qtTeamTalk/preferencesdlg.cpp

Assertion appears when going to Shortcuts-tab, then General-tab and pressing OK in Preferences dialog.
Also optimize storing hotkeys.

Fix empty PPT hotkey assertion

---

Client/qtTeamTalk/languages/ko.ts

I updated the Korean translations of qtTeamTalk to be compatible with the latest version.
Thank you.

updated the Korean translations of qtTeamTalk

---

Client/qtTeamTalk/userinfodlg.cpp

Fix a bug reported by user after change to QLabel for User Info dialog

Display IP address in user info if USERRIGHT_BAN_USERS

---

ChangeLog.txt
Client/qtTeamTalk/changestatus.ui
Client/qtTeamTalk/changestatusdlg.cpp
Client/qtTeamTalk/preferences.ui
Client/qtTeamTalk/preferencesdlg.cpp

An user request was made to replace radio button by comboboxes.
@bear101 Is it OK? If yes, I can continue

Replace radio button by comboboxes in some dialogs

---

Library/TeamTalkLib/build/ffmpeg/CMakeLists.txt

FFmpeg build fixes

---

Client/qtTeamTalk/languages/de.ts

Fixed a wrong gender and added some missing strings.

Updated german Qt client interface

---

Client/qtTeamTalk/mainwindow.ui

Restore selection mode and behaviour on file list
Reported in #2482

Fix file deletion

---

ChangeLog.txt
Client/TeamTalkAndroid/src/main/java/dk/bearware/backend/TeamTalkService.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/data/TextMessageAdapter.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java
Client/TeamTalkAndroid/src/main/res/menu/main.xml
Client/TeamTalkAndroid/src/main/res/values/strings.xml

with in less than 24 hours of opening issue about adding broadcast ability to teamtalk android, I did it! Use and enjoy it!

android client. Added broadcast message sending ability

---

Client/qtTeamTalk/utilxml.cpp

Same as "rememberLastChannel" in Android client.
@amirmahdifard this is to support your changes in #2562

Store and load last-joined-channel in .tt file

---

ChangeLog.txt
Client/qtTeamTalk/CMakeLists.txt
Client/qtTeamTalk/chattextedit.cpp
Client/qtTeamTalk/chattextedit.h
Client/qtTeamTalk/chattextlist.cpp
Client/qtTeamTalk/chattextlist.h
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h
Client/qtTeamTalk/mainwindow.ui
Client/qtTeamTalk/preferences.ui
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/settings.h
Client/qtTeamTalk/textmessage.ui
Client/qtTeamTalk/textmessagedlg.cpp
Client/qtTeamTalk/textmessagedlg.h

This is a continuation of #2548.
@CoBC there's a bug in the text message popup dialog so there's an edit field appearing. Any idea why this is happening?

Configurable Chat History as List view

---

Client/qtTeamTalk/mainwindow.cpp

Fixes issue where edit field is above the history.

Insert ChatTextList/ChatTextEdit at correct index

---

ChangeLog.txt
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java
Client/TeamTalkAndroid/src/main/res/menu/user_actions.xml
Client/TeamTalkAndroid/src/main/res/values/strings.xml

Currently only user menu action for message, But there will be more, for eas of access, and to more sink desktop client

android. Add some new actions for eas of access

---

Client/qtTeamTalk/mainwindow.cpp

Fix tab order for ChatTextEdit/ChatTextList and ChatLineEdit

---

Client/qtTeamTalk/chattextlist.cpp
Client/qtTeamTalk/chattextlist.h

* Copy=CTRL+C
* View Details=CTRL+Enter
* Copy All=CTRL+Shift+C
* Clear=CTRL+Shift+Delete

Add shortcuts to ChatTextList context menu action

---

Client/qtTeamTalk/mainwindow.cpp

Fix tray icon not updating when leaving channel

---

Client/qtTeamTalk/onlineusersdlg.cpp
Client/qtTeamTalk/onlineusersdlg.h

QAction only defined one time in constructor

Simplify onlineusersdlg context menu creation

---

.github/workflows/ios.yml

Uses upload/download GitHub Actions

Publish iOS universal binary as artifact

---

Client/qtTeamTalk/languages/de.ts

Chat templates and other minor fixes.

Updated german Qt translation

---

Client/qtTeamTalk/preferences.ui
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/preferencesdlg.h

Also use suffix instead of different label to display bitrate unit

Replace radiobuttons by Combobox in video capture tab

---

Client/qtTeamTalk/chattemplatesdlg.cpp
Client/qtTeamTalk/chattextedit.cpp
Client/qtTeamTalk/chattextlist.cpp
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/preferencesdlg.h
Client/qtTeamTalk/settings.h
Client/qtTeamTalk/utilui.cpp
Client/qtTeamTalk/utilui.h

Add server and channel specific messages to templates

---

ChangeLog.txt
Client/TeamTalkAndroid/src/main/java/dk/bearware/backend/TeamTalkService.java

Fix speaker not being reenabled when disabling voice activation

---

Client/qtTeamTalk/chattextlist.cpp

Only treat message content when searching URLs

---

Client/qtTeamTalk/languages/de.ts

Translated missing lastminute additions, minor corrections.

Updated german Qt interface

---

Library/TeamTalkJNI/src/dk/bearware/Constants.java

Should be 0xFFF but was 0xFFFF

Fix TT_CLASSROOM_FREEFORALL value for Java

---

Client/qtTeamTalk/mainwindow.cpp

@bear101 Please review this. I'm unable to test it currently. If it works, please merge, as many users would benefit from this change.

Feat: Auto-switch to new default sound device

---

Client/qtTeamTalk/languages/fa.ts

New strings for v5.19 has been translated to Persian

Update Persian QT Translation

---

.github/dependabot.yml

This reverts commit eda5e09e28d13e2fe8cdc4c01b5e393c69841285.

Revert "Add /Library/TeamTalkLib/test/catchqt/TeamTalkCatchQT/android"

---

ChangeLog.txt
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java
Client/TeamTalkAndroid/src/main/res/menu/main.xml
Client/TeamTalkAndroid/src/main/res/values/strings.xml

like qt client, there is now a seperet leave action that allows you to leave your current channel from everywhere

android. Added action to leave channels

---

Client/TeamTalkAndroid/src/main/res/values-de/strings.xml
Client/qtTeamTalk/languages/de.ts

Qt and Android. Please take a closer look at the updated Android language file As a precaution. Code should be OK, but I used a script to save time when copying the new strings from the values folder. 🙂

Updated german locales

---

Client/TeamTalkAndroid/src/main/res/xml/pref_about.xml

until now, my contribution to teamtalk android are as follows.
- Online users activity now has popup menu contaning all user actions
- Added a new option to prevent talking users from moving to the top of users list
- Added the ability to leave channels
- Added the ability to set status messages
- Added the ability to control user's transmissions
- Option to automatically join root channel in preferences
- Announce who is channel operator
- Announce who is selected for moving to other channel
- Ability to play sound when voice activation is toggled
- Ability to play sound for intercept subscription toggled
- Ability to use Text-To-Speech to announce transmission changes
- Ability to use Text-To-Speech to announce subscription changes
- Fixed bug where user's status message is not …

Android. Added my name

---

Build/Docker/Dockerfile_android
Build/Docker/Dockerfile_ubuntu22
Build/Docker/Dockerfile_ubuntu24
Build/Makefile

- Enhance TEAMTALK_ROOT and ANDROID_NDK_HOME validation with directory existence check
- Replace update-alternatives with python-is-python3 package

Improve Makefile robustness and Python setup

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mytableview.cpp
Client/qtTeamTalk/mytableview.h
Client/qtTeamTalk/preferences.ui
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/settings.h

Reintroduce option to speak tree item using TTS on MacOS

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h

Should fixes #2795
@bear101 Can you test please? I'm not able to test on macOS for now :(

Call slotClientExit() on close event

---

Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/EdgeToEdgeHelper.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/ServerListActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/WebLoginActivity.java

Enabled EdgeToEdge for android 15+
Please check visually on android 15+ and android 10-14
fixes #2815

Fix UI overlap in android 15 and above

---

.github/workflows/update-gradle-wrapper.yml

A Workflow Dispatch trigger has been added, and execution conditions in scheduled runs have been optimized.

Fix Gradle Wrapper Update Action

---

.github/workflows/android.yml
Build/Docker/Dockerfile_android
Build/Makefile
Client/TeamTalkAndroid/build.gradle

Downgraded to JDK 17 on TeamTalkAndroid

---

CMakeLists.txt
Client/TeamTalkClassic/CMakeLists.txt
Library/TeamTalkLib/CMakeLists.txt
Library/TeamTalkLib/README.md
Library/TeamTalkLib/build/ace/CMakeLists.txt
Library/TeamTalkLib/build/libvpx/CMakeLists.txt

VS2022 uses PlatformToolset=v143

Remove /property:PlatformToolset=v142 from msbuild command

---

.github/workflows/windows.yml

I also simplified the name of the Yasm installation section and fixed triplet issues.

Install Cygwin instead of MSYS2
