TeamTalkAndroid/src/main/res/values-tr/strings.xml
iTeamTalk/iTeamTalk/tr.lproj/Localizable.strings

If Headset TX Toggle option was enabled, master volume is not changed. We tried to set the master volume with both headset buttons and phone buttons.

Turkish translations and an issue

---

qtTeamTalk/languages/German.ts

* Removed translation of keyboard shortcuts to make them work again (fixes #251)
* other small and cosmetic fixes
Can someone test this on MacOS please? Windows and linux clients are working.

Update german Qt translation

---

Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java
Client/TeamTalkAndroid/src/main/res/layout/item_info.xml

It appears to be more or less common practice to publish
announcements, schedules, and other info via channel items. Such
channels usually have maximum users limit set to 0. In this sense they
are dummy, i.e. not joinable. Thus there is no reson to keep
corresponding button. Since text fields of the item bear useful
information, it seems rational to make them multiline in order to
avoid cropping. And, at last, these info items should be displayed at
the top of list. All this is implemented here.
Maybe, there is another way, more natural and elegant?
Of course, I know that server can pass general info to clients via
messages. But it seems to be less convenient, since requires shift to
another tab where general info becomes lost in other messages.

Dummy channels as pure info items

---

Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/PreferencesActivity.java

Native mechanism is used to distinguish screen sizes and deploy
two-panel layout when it is appropriate. Otherwise settings are
organized hierarchically.

Android client: hierarchical preferences navigation

---

ChangeLog.txt
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/Utils.java

Here is a solution for couple of issues discussed in #530. Sticky
channels are moved to the very top of list, just before users, and
back button can be used for navigation to the parent channel. Back
button behaviour is modified only for channels tab. In other tabs it
closes connection and returns to the server list as earlier.

Channel list organization in Android client

---

Client/iTeamTalk/iTeamTalk/Base.lproj/Localizable.strings
Client/iTeamTalk/iTeamTalk/ChannelListViewController.swift
Client/iTeamTalk/iTeamTalk/MainTabBarController.swift
Client/iTeamTalk/iTeamTalk/ar.lproj/Localizable.strings
Client/iTeamTalk/iTeamTalk/da.lproj/Localizable.strings
Client/iTeamTalk/iTeamTalk/de.lproj/Localizable.strings
Client/iTeamTalk/iTeamTalk/en.lproj/Localizable.strings
Client/iTeamTalk/iTeamTalk/es.lproj/Localizable.strings
Client/iTeamTalk/iTeamTalk/fr.lproj/Localizable.strings
Client/iTeamTalk/iTeamTalk/hu.lproj/Localizable.strings
Client/iTeamTalk/iTeamTalk/it.lproj/Localizable.strings
Client/iTeamTalk/iTeamTalk/nl.lproj/Localizable.strings
Client/iTeamTalk/iTeamTalk/pl.lproj/Localizable.strings
Client/iTeamTalk/iTeamTalk/pt-BR.lproj/Localizable.strings
Client/iTeamTalk/iTeamTalk/ru.lproj/Localizable.strings
Client/iTeamTalk/iTeamTalk/tr.lproj/Localizable.strings
Client/iTeamTalk/iTeamTalk/zh.lproj/Localizable.strings

- Add an accessibility value to say if tx button is on or off
- Return who has kicked
- Change title for private messages to return nickname
Unfortunately I can't test changes for iOS at moment. @bear101 please let me know if something should be change. If it's OK for you, could you update translations, after that a new beta will be appreciated.

Small fixes for iTeamTalk

---

Library/TeamTalkLib/avstream/MFStreamer.cpp

I left a debug log in the previous commit that uses a trace statement that I keep locally.

Remove non-compiling debug logging

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp

I found alternative way to archive what you're trying to do in PR #855.
This new PR also solves an issue where the password of a temporary channel is not recreated for the person who initially created it.
This new PR also solves when you left the channel and don't want to rejoin.

Rejoin 'm_last_channel'

---

Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java

A new try to apply better changes to status description in Android client.
With my latest PR, description is set to away when an user switch to this mode, but when switch again to another one, description isn't reset.

Set status description to away only when appropriate

---

Client/qtTeamTalk/mainwindow.cpp

Very useful on Windows to use option "Copy as file path" of files explorer and past this to CTRL-S dialog.

QT - Fix streaming of files path containing quote

---

Library/TeamTalkJNI/test/dk/bearware/TeamTalkTestCase.java
Library/TeamTalkLib/codec/MediaUtil.cpp
Library/TeamTalkLib/codec/MediaUtil.h
Library/TeamTalkLib/teamtalk/CodecCommon.cpp
Library/TeamTalkLib/teamtalk/CodecCommon.h
Library/TeamTalkLib/teamtalk/client/AudioMuxer.cpp
Library/TeamTalkLib/teamtalk/client/AudioMuxer.h
Library/TeamTalkLib/teamtalk/client/ClientNode.cpp
Library/TeamTalkLib/test/CatchDefault.cpp
Library/TeamTalkLib/test/TTUnitTest.h
Library/TeamTalk_DLL/TeamTalk.h

When not in a channel calling `TT_EnableAudioBlockEventEx(ttInst, TT_MUXED_USERID, STREAMTYPE_VOICE, fmt, TRUE)` will now cause TTInstance to output AudioBlock's containing silence. The AudioBlocks will use a frame size of 20 msec when 'fmt' is specified.

TT_EnableAudioBlockEvent outside channel for TT_MUXED_USERID

---

ChangeLog.txt
Client/qtTeamTalk/streammediafiledlg.cpp
Client/qtTeamTalk/streammediafiledlg.h

This fix issues caused by commit 2356b05:
- It's not anymore require to press enter twice to stream a file
- This also fix a regression with Orca screen reader which has some dificulties to read combobox after commit above
With this PR, if combobox's index is 0, cursor position is also 0 and user paste a text from clipboard, current text of combobox is replaced by newest.
If one of this conditions isn't respect, text is simply paste without any replacement.

QT - Fixed issues caused by 2356b05

---

Client/qtTeamTalk/serverlistdlg.cpp

With this PR, if latest host is save in known hosts, it's selected when opening serverlist class and listWidget get the focus, otherwise hostaddrBox get focus and no server is selected in listWidget.
I tested behavior expected in issue #915 and it's working correctly now.

QT - Only select server if lastest host is an existing entry

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/preferences.ui
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/settings.h

Can you check that "push-to-talk lock" is always disabled on Linux and follows the "normal" push-to-talk?

Push To Talk lock. Issue #278

---

Client/qtTeamTalk/common.cpp
Client/qtTeamTalk/common.h
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/serverlistdlg.cpp

After commit 27f2a75 of PR #940, change nickname when connecting only update latesthost, change wasn't save to serverentry.
This issue is due to sameHost and sameHostEntry which always check nickname corresponding. This PR add a parameter to this functions to make nickname check optional.
When call dialog to change nickname, sameHost and sameHostEntry are now call without checking nickname, and issue described above is fix.

QT - Fix sameHost and sameHostEntry when checking for nickname changes

---

Client/qtTeamTalk/mainwindow.cpp

Now that nickname can be change for server or globally, we have to clarify text of dialog box and menu item.

Qt - Clarify texts for nickname change

---

ChangeLog.txt
Client/qtTeamTalk/onlineusersdlg.cpp
Client/qtTeamTalk/onlineusersdlg.h

If necessary, we can retrieve the existing translations from ts files because the text copy to clipboard is the same as the text using for accessible text role.
I precise this point in case this feature has to be include in 5.8.1 and to avoid waiting for new translations.

Copy user infos using CTRL+C from online users dialog

---

Client/qtTeamTalk/mainwindow.cpp

Oddly 'Quit' menu item in French translation is disable but still works.
Fixes #1109
I hope this doesn't screw up #994 again w.r.t. Alt+F4

Manually specify quit keyboard sequence

---

Client/qtTeamTalk/channelstree.cpp

For now when an user is speaking and don't have a status message define, emojis 🎤 and 👨 or 👩 are not separate, which can cause confuse and some users requested a little break with screen reader.
So, this PR introduce a coma bitween emojis when user hasn't status message, which force synthetisor to make a small break bitween emojis.

Coma bitween micro and gender emoji

---

Client/qtTeamTalk/Entitlements.plist
Library/TeamTalkLib/teamtalk/client/ClientNodeBase.cpp
Library/TeamTalkLib/teamtalk/client/ClientNodeBase.h

Replace ACE_Semaphore by std::conditional_variable.
Fixes crash issue in AppStore version when starting second instance.
Reported in issue #1145

Fixed crash issue when starting second instance on macOS

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yml

I've set up two templates that people will have to fill out when creating an issue. One for bug reports and one for feature requests.
Many issues lack information, so hopefully this will make people more through before submitting issues. Also people should use Discussions more before creating an issue. Often the feature they request can be obtained in some other way using existing functionality.

Templates for creating issues

---

Client/qtTeamTalk/mainwindow.cpp

This fixes issue described in #1020.
This can easily break something but it simplifies the join process. Basically szInitChannel should take priority over user's stored setting and is otherwise treated the same with regard to channel creation. I.e. if parent existing then create a new channel. Previous szInitChannel only worked if the channel already existed.

Favor UserAccount.szInitChannel over user's stored join setting

---

Client/qtTeamTalk/common.cpp
Client/qtTeamTalk/common.h
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/serverlistdlg.cpp

Previously, sameHost checked if name = host.name, but in case of BearWare accounts usage, username defined in host entry is not really the same as used to login. This caused nickname changes to don't take effect if a server was saved using a BearWare account. This PR add a check to sameHost to see if username is BearWare or ends with @bearware.dk, and we can now change nicknames correctly for servers with BearWare accounts.

Fix nickname change for servers with BearWare accounts

---

Library/TeamTalkLib/teamtalk/client/ClientNodeBase.cpp
Library/TeamTalkLib/teamtalk/ttassert.h

This fixes race condition when checking ACE_Reactor's owner in
ClientNode::Connect(). ASSERT_NOT_REACTOR_THREAD would fail with
invalid reactor owner.

Set reactor's thread ID prior to notify

---

Library/TeamTalkLib/bin/ttsrv/ServerGuard.cpp
Library/TeamTalkLib/teamtalk/server/ServerChannel.cpp
Library/TeamTalkLib/teamtalk/server/ServerChannel.h
Library/TeamTalkLib/teamtalk/server/ServerNode.cpp
Library/TeamTalkLib/teamtalk/server/ServerNode.h

Transmit users queue clean up as well to use same channel update methods.
Fixes #321

Log message on transmit user changing

---

ChangeLog.txt
Client/qtTeamTalk/common.cpp
Client/qtTeamTalk/common.h
Client/qtTeamTalk/serverlist.ui
Client/qtTeamTalk/serverlistdlg.cpp
Client/qtTeamTalk/serverlistdlg.h
Client/qtTeamTalk/settings.h
Client/qtTeamTalk/utilui.cpp
Client/qtTeamTalk/utilui.h

I plan to run a service that updates the number of currently active users and MOTD every 5 minutes. At the moment the service is not running but you should be able to see the feature anyway.
Can you look into making the server list items accessible?
https://github.com/BearWare/TeamTalk5/blob/serverlist/Client/qtTeamTalk/serverlistdlg.cpp#L107

See MOTD as tooltip and currently active users

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/settings.h
Client/qtTeamTalk/utilui.cpp
Client/qtTeamTalk/utilui.h

@bear101 If you are agree with changes in this PR, can you look to make settings choose at first startup to directly take effects? For now we have to restart TT or open and close preferences to apply settings choose at first startup.

Choose language at first startup

---

Library/TeamTalkLib/bin/ttsrv/Main.cpp
Library/TeamTalkLib/teamtalk/client/ClientNodeBase.cpp
Library/TeamTalkLib/teamtalk/client/ClientNodeBase.h

Use monotonic timer (ACE_High_Res_Timer ) instead of absolute timer for ACE_Reactor::schedule_timer(), i.e. change ACE_Timer_Queue on ACE_Reactor to use gettimeofday_hr() instead of gettimeofday().
Fixes #1346

Use monotonic timer instead of absolute timer

---

.github/workflows/android.yml

Ensure to use Android NDK r21 otherwise various libraries will fail to build (e.g. OpenSSL, LibVPX).
Android NDK releases are notorious for breaking compatibility :disappointed:

Make workflow use Android NDK r21

---

Client/qtTeamTalk/mainwindow.cpp

I'm currently using IBMTTS or known as Eloquence. When I press Control+T, it will read with the following way.
RX: 0.01KB TX: 2.70KB P I N G: 16
Q: Why it will happend?
A: Because It has no space after TX: x.xxKB and the word "PING" is all in capital letter.
Example: RX: 0.01KB TX: 2.70KBPING: 16
Fix: I add the space between the TX: %2KB and the quotation mark (").
It Should Be: RX: 0.01KB TX: 2.70KB PING: 16

Try to fix the weird TTS pronunciation

---

Client/qtTeamTalk/mainwindow.cpp

This prevents the username to be pronounced twice

Only send full message to TTS, not origin and full message

---

Client/qtTeamTalk/mainwindow.cpp

Following PR #1383, sounds played at startup has changed. This PR call enableVoiceActivation directly with correct sounds at startup instead of slotMeEnableVoiceActivation.

Fix startup sounds

---

Client/qtTeamTalk/channelstree.cpp

Item state is now natively accessible with Qt6.4.

Remove "Expanded" or "Collapsed" from channels tree with Qt6.4 and beyond

---

Client/qtTeamTalk/keycompdlg.cpp
Client/qtTeamTalk/keycompdlg.h
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h

According to the Qt documentation, nativeEvent now use qintptr* result instead of long* result. This PR make this change.

Convert overloaded nativeEvent to Qt6

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp

I think this is a simpler way to start a new instance in the same profile.
With this change we can put "noconnect" argument in "Current Profile". This would solve #1297

Ability to start new instance in current profile

---

Client/qtTeamTalk/mainwindow.cpp

User's OS can be determined in all other clients (Android and iOS directly in client name, and classic client only available on Windows).
In case it can be helpfull (for help for example) this PR display OS type in client field of users informations.

Return OS type in addition to client name at login

---

Client/qtTeamTalk/ttseventsmodel.cpp

@CoBC Is there any need to two columns to show checked/unchecked TTS events in Qt 5?

Single column for showing checked/unchecked TTS events

---

.gitignore
Build/.gitignore
Client/TeamTalkClassic/CMakeLists.txt
Client/qtTeamTalk/qt/CMakeLists.txt
Library/TeamTalkLib/build/ace/CMakeLists.txt
Library/TeamTalkLib/build/libvpx/CMakeLists.txt
Library/TeamTalkLib/build/libvpx/build-libvpx-win.bat_sample
Library/TeamTalkLib/build/ogg/0001-Add-d-suffix-to-debug-build-and-switch-to-MT.patch
Library/TeamTalkLib/build/ogg/CMakeLists.txt
Library/TeamTalkLib/build/openssl/CMakeLists.txt
Library/TeamTalkLib/build/opus/0001-Add-d-suffix-to-debug-build-and-MT-option.patch
Library/TeamTalkLib/build/opus/CMakeLists.txt
Library/TeamTalkLib/build/portaudio/CMakeLists.txt
Library/TeamTalkLib/build/speex/CMakeLists.txt
Library/TeamTalkLib/build/speexdsp/CMakeLists.txt
Library/TeamTalkLib/build/tinyxml/CMakeLists.txt
Library/TeamTalkLib/build/webrtc/CMakeLists.txt
Library/TeamTalkLib/build/zlib/CMakeLists.txt

Previously CMAKE_VS_PLATFORM_NAME was expected to be set in order to compile. However, CMAKE_VS_PLATFORM_NAME is not set by Ninja on Windows. With the changes in this merge request the CMAKE_VS_PLATFORM_NAME variable is no longer required.
Also ACE, OPUS, OGG has switched to patching instead of pointing to a git-hash. This makes it easier to upgrade these dependencies.
A side effect is also that it should be possible to build from Qt Creator on Windows.

Ability to use BUILD_TEAMTALK_CORE in Ninja builds on Windows

---

Client/qtTeamTalk/aboutdlg.cpp

I thought that this information can be usefull now that we have ability to build using Qt5 or Qt6. We can maybe also add the Qt's version currently using by the app? @bear101 what do you think?

Return Qt version on about dialog

---

ChangeLog.txt
Client/qtTeamTalk/aboutdlg.cpp

PR #1436 added display of Qt's version used when building. This PR also display version used by the app when running.

Display Qt version used

---

Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mytreeview.cpp
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/settings.h

In Qt6, list are natively accessible using arrow keys on MacOS, so option to speak list using TTS is no longer useful.

Remove speak list option on Qt6

---

ChangeLog.txt
Library/TeamTalkLib/teamtalk/server/ServerChannel.cpp
Library/TeamTalkLib/teamtalk/server/ServerChannel.h
Library/TeamTalkLib/teamtalk/server/ServerNode.cpp

The <channelbans> on <channel> tag contains <channel-path> which must
be updated if channel is renamed. Otherwise the BANTYPE_CHANNEL will
be invalid.
This fixes #414

Update channel path when renaming a channel

---

Client/qtTeamTalk/channeldlg.cpp
Client/qtTeamTalk/serverpropertiesdlg.cpp

This allow users to see most information as possible using keyboard even if they don't have right to edit properties of channel or server.
@bear101 Do you have any idea on how to do a similar thing for checkboxes, comboboxes and sliders?

Make lineEdit and spinBox readonly instead of disabled

---

ChangeLog.txt
Library/TeamTalkJNI/test/dk/bearware/TeamTalkServerTestCase.java
Library/TeamTalkLib/teamtalk/Channel.h
Library/TeamTalkLib/teamtalk/server/ServerChannel.cpp
Library/TeamTalkLib/teamtalk/server/ServerChannel.h
Library/TeamTalkLib/teamtalk/server/ServerNode.cpp

Also kick/ban from non-participating channels.
Fixes #1496

Auto-operators can update non-participating channels

---

Client/qtTeamTalk/common.cpp

Otherwise crashes on macOS 11.7. Fixes #1503

Revert to deprecated kIOMasterPortDefault instead of kIOMainPortDefault

---

ChangeLog.txt
Client/qtTeamTalk/onlineusersdlg.cpp
Client/qtTeamTalk/onlineusersdlg.h

@CoBC I don't know if you already tried this but I'm trying to make shortcut keys work in "Online Users" dialog.
With the changes in this merge request it's possible to do operations with shortcuts. However, shortcut will only work if no user is selected in the main-window (i.e. menu items in "Users" are disabled). Any idea how to get around this?

Shortcut keys in 'Online Users' dialog

---

Client/qtTeamTalk/textmessage.ui

I think "Close" is more logic than "Cancel" in this dialog because we don't really cancel anything, but we close text message window using this button.

Rename "Cancel" button to "Close" on text message dialog

---

Client/qtTeamTalk/chattextedit.cpp

The rest of the event is pretty explicit in my opinion, it reduces the size of the event

Remove "Joined new channel" from event when joining a channel

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp

Focusing this window automatically can cause accessibility issue.
If user write a public message and receive a private one, the end of the message will be sent to the private conversation.

Don't focus text message window automatically at all

---

Client/qtTeamTalk/mainwindow.cpp

Initialization of sound devices occurred several different places depending on the current state of ttInst. To simplify things we just initialize sound devices on startup and then reinitialize if user changes sound devices in preferences.

Initialize sound devices on startup

---

Library/TeamTalkLib/teamtalk/server/ServerUser.cpp

In the same way as disk quota.

Inherit maximum users in temporary channels from server properties

---

Client/qtTeamTalk/mainwindow.cpp

Doing so will prevent sound events from being played after disconnect when using one-by-one or overlapped (using TeamTalk sound device).
This fixes #1650

Don't close sound devices on disconnect

---

Client/qtTeamTalk/about.ui
Client/qtTeamTalk/bannedusers.ui
Client/qtTeamTalk/channel.ui
Client/qtTeamTalk/filetransfer.ui
Client/qtTeamTalk/keycomp.ui
Client/qtTeamTalk/mainwindow.ui
Client/qtTeamTalk/preferences.ui
Client/qtTeamTalk/serverlist.ui
Client/qtTeamTalk/serverproperties.ui
Client/qtTeamTalk/textmessage.ui
Client/qtTeamTalk/userdesktop.ui
Client/qtTeamTalk/userinfo.ui
Client/qtTeamTalk/uservideo.ui
Client/qtTeamTalk/uservolume.ui

AnyTerritory is incompatible with Qt 5 so the property should never be set.

Remove <property name="locale"> it becomes AnyTerritory in Qt Creator

---

Library/TeamTalkJNI/test/dk/bearware/TeamTalkServerTestCase.java
Library/TeamTalkLib/teamtalk/server/ServerNode.cpp

Limit file upload to users of the channel or admins (since they're the only ones who can see the file afterwards).

Prevent file upload outside own channel (unless admin)

---

Library/TeamTalkLib/myace/MyACE.cpp

TARGET_OS_IPHONE and TARGET_OS_SIMULATOR are either 0 or 1

Do not use 'defined' TARGET_OS_IPHONE and TARGET_OS_SIMULATOR

---

Library/TeamTalkJNI/test/dk/bearware/TeamTalkServerTestCase.java

testDnsResolve now runs in encrypted mode as well

---

.github/workflows/android.yml
.github/workflows/smoketest.yml
.github/workflows/windows.yml
Build/Makefile
CMakeLists.txt
Library/TeamTalkLib/README.md

Only when using downloaded TeamTalk SDK the BUILD_TEAMTALK_CORE should be OFF.

Default BUILD_TEAMTALK_CORE to ON

---

Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h

QMainWindow::Connect() and QMainWindow::Disonnect() have been rename, so they are not confused with QObject::connect/disconnect.

Rename connect/disconnect to server in QtTeamTalk

---

Library/TeamTalkPy/TeamTalk5.py

Implement the following methods to TeamTalkPy:
* doChannelOp
* doMoveUser
* doBanUser
* doBanIPAddress
* doUnBanUser
Some asked function in #1781 are in this PR, by @lbk2907 and @yukie-nobuharu
@DalisonCPU as you did not reply, I managed to implement DoMoveUser.

Implement some moderation function to TeamTalkPy

---

Library/TeamTalkPy/TeamTalk5.py

Implement client/server commands which were not implemented in TeamTalkPy and their respective event when applicable.
`CLIENTEVENT_STREAM_MEDIAFILE` is also added.

Implement remaining not implemented do methods and their respective events in TeamTalkPy

---

Library/TeamTalkPy/TeamTalk5.py

The same logic is applied in qTeamTalk and avoid the last character of first messages to be removed when building a long message which will be sent in multiple parts.
Also use the `TT_STRLEN` constent instead of hard-coding the value.

Use TT_STRLEN-1 instead of 512 in buildTextMessage for TeamTalkPy

---

Library/TeamTalk_DLL/TeamTalk.h

- Replace useraccount by banneduser for CLIENTEVENT_CMD_BANNEDUSER
- Escape unescaped percentage symbols

Fix SDK documentation for banned user event and escape remaining unescaped percentage symbols

---

Library/TeamTalkPy/TeamTalk5.py

Called when client event is CLIENTEVENT_INTERNAL_ERROR

Add onInternalError to TeamTalkPy

---

Library/TeamTalkLib/bin/ttsrv/ServerConfig.cpp
Library/TeamTalkLib/mystd/MyStd.cpp
Library/TeamTalkLib/mystd/MyStd.h
Library/TeamTalkLib/teamtalk/Common.cpp
Library/TeamTalkLib/teamtalk/Common.h

This prevents std::regex_error exception on invalid regex

Change std::regex construction to buildregex()

---

Library/TeamTalkJNI/test/dk/bearware/TeamTalkTestCase.java

This was the main reason for the v5.13.1 release.

Test verifying exception std::regex_error is not thrown

---

Library/TeamTalkPy/TeamTalk5.py

Implement TeamTalk5 SDK 5.13A API changes:
* `CLIENTEVENT_CON_CRYPT_ERROR` and it its evens method
* `CLIENTEVENT_CMD_USERACCOUNT_NEW` and `CLIENTEVENT_CMD_USERACCOUNT_REMOVE` with respective event methods
* `sounddevice` field in `ttmessage` and `CLIENTEVENT_SOUNDDEVICE_ADDED`, `CLIENTEVENT_SOUNDDEVICE_REMOVED`, `CLIENTEVENT_SOUNDDEVICE_UNPLUGGED`, `CLIENTEVENT_SOUNDDEVICE_NEW_DEFAULT_INPUT`, `CLIENTEVENT_SOUNDDEVICE_NEW_DEFAULT_OUTPUT`, `CLIENTEVENT_SOUNDDEVICE_NEW_DEFAULT_INPUT_COMDEVICE`, `CLIENTEVENT_SOUNDDEVICE_NEW_DEFAULT_OUTPUT_COMDEVICE` with respective class methods

Implement SDK 5.13A new features to TeamTalk Py

---

Client/TeamTalkAndroid/src/main/java/dk/bearware/data/TTSWrapper.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java
Client/TeamTalkAndroid/src/main/res/values/strings.xml
Client/TeamTalkAndroid/src/main/res/xml/pref_tts.xml

which will be cought and spoken by running accessibility service
Needs to be tested.
In my testing, while speaking, it may skip some events.
Don't know how to resolve it yet.

It is now possible to send tts-messages as Accessibility announcements

---

ChangeLog.txt
Library/TeamTalkJNI/test/dk/bearware/TeamTalkServerTestCase.java
Library/TeamTalkLib/teamtalk/server/ServerNode.cpp
Library/TeamTalkLib/teamtalk/server/ServerNode.h

If a user has USERRIGHT_MOVE_USERS then it was possible to move a user who had no yet logged in.

Do not allow user to move user who is not logged in

---

ChangeLog.txt
Client/qtTeamTalk/utilsound.cpp

So far this is only supported on Windows.

Favour default communication device instead of PortAudio default device

---

Client/TeamTalkAndroid/src/main/java/dk/bearware/backend/TeamTalkService.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/data/DesktopAdapter.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/data/FileListAdapter.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/data/MediaAdapter.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/data/MediaFileVideoAdapter.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/data/WebcamAdapter.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/ChannelPropActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/ServerEntryActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/ServerListActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/TextMessageActivity.java
Library/TeamTalkJNI/CMakeLists.txt
Library/TeamTalkJNI/src/dk/bearware/events/ClientEventListener.java
Library/TeamTalkJNI/src/dk/bearware/events/ClientListener.java
Library/TeamTalkJNI/src/dk/bearware/events/CommandListener.java
Library/TeamTalkJNI/src/dk/bearware/events/ConnectionListener.java
Library/TeamTalkJNI/src/dk/bearware/events/TeamTalkEventHandler.java
Library/TeamTalkJNI/src/dk/bearware/events/UserListener.java

Previously a class would have to implement all methods of interfaces UserListener, ClientListener, CommandsListener and ConnectionListener. With this change it's possible to register only a subset of events.

Separate event callback for each ClientEvent

---

Client/TeamTalkAndroid/src/main/java/dk/bearware/backend/TeamTalkService.java
Library/TeamTalkJNI/src/dk/bearware/EncryptionContext.java

Align default value of bVerifyClientOnce to false (like C++) and set nVerifyDepth = -1 when no peer verification should take place.

bVerifyClientOnce or nVerifyDepth >= 0 will force certificate verification

---

ChangeLog.txt
Library/TeamTalkLib/teamtalk/Commands.cpp

Stack trace:
0  0x00005555556f6948 in teamtalk::ServerUser::DoShowBan(teamtalk::BannedUser const&) ()
1  0x00005555556c3fb6 in teamtalk::ServerNode::UserListServerBans(int, int, int, int) ()
2  0x00005555556f3d79 in teamtalk::ServerUser::HandleListServerBans(std::map<ACE_String_Base<char>, ACE_String_Base<char>, std::less<ACE_String_Base<char> >, std::allocator<std::pair<ACE_String_Base<char> const, ACE_String_Base<char> > > > const&)
()
3  0x00005555557024d3 in teamtalk::ServerUser::HandleCommand(ACE_String_Base<char> const&, std::map<ACE_String_Base<char>, ACE_String_Base<char>, std::less<ACE_String_Base<char> >, std::allocator<std::pair<ACE_String_Base<char> const, ACE_String_Base<char> > > > const&) ()
4  0x00005555557071d2 in teamtalk::ServerUser::ProcessCommand(ACE_String_Base<char> …

Fix crash issue if std::gmtime() returns nullptr in DoShowBan

---

Library/TeamTalkLib/bin/ttsrv/ServerGuard.cpp
Library/TeamTalkLib/teamtalk/server/ServerNode.cpp

After introduced of 'authenticated' ServerNode::GetUser() (git hash ba0d2770ce) it is not possible do BearWare.dk WebLogin.

Fix empty access-token for BearWare.dk WebLogin

---

ChangeLog.txt
Client/qtTeamTalk/channel.ui
Client/qtTeamTalk/channeldlg.cpp
Library/TeamTalk.NET/TeamTalk.cs
Library/TeamTalkJNI/jni/ttconvert-jni.cpp
Library/TeamTalkJNI/src/dk/bearware/Channel.java
Library/TeamTalkJNI/test/dk/bearware/TeamTalkServerTestCase.java
Library/TeamTalkJNI/test/dk/bearware/TeamTalkTestCase.java
Library/TeamTalkLib/bin/dll/Convert.cpp
Library/TeamTalkLib/bin/ttsrv/ServerXML.cpp
Library/TeamTalkLib/teamtalk/Channel.h
Library/TeamTalkLib/teamtalk/Commands.h
Library/TeamTalkLib/teamtalk/Common.h
Library/TeamTalkLib/teamtalk/client/ClientNode.cpp
Library/TeamTalkLib/teamtalk/server/ServerChannel.cpp
Library/TeamTalkLib/teamtalk/server/ServerChannel.h
Library/TeamTalkLib/teamtalk/server/ServerNode.cpp
Library/TeamTalkLib/teamtalk/server/ServerUser.cpp
Library/TeamTalkPy/TeamTalk5.py
Library/TeamTalk_DLL/TeamTalk.h

This fixes #22.
A voice or media file stream can be limited to last a maximum duration after which they are blocked. User will have to toggle PTT to transmit again for voice stream. Media file stream will have to be restarted.

Time out Timer for voice and media files

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/settings.h

@CoBC I've simplified it a bit by just using subscribeCommon() which is already there. Also as I've mentioned earlier I'm not a big fan of [QObject::sender()](https://doc.qt.io/qt-6/qobject.html#sender).

Restore 'Hear myself' upon new connection

---

Library/TeamTalkLib/bin/dll/TeamTalk.cpp
Library/TeamTalk_DLL/TeamTalk.h

Added missing TT types to corresponding enum and cases in DBG_SIZEOF because without this size comparisons of these structs will fail

add missing TT types To enum

---

Library/TeamTalk.NET/TeamTalk.cs
Library/TeamTalk.NET/TeamTalkSrv.cs
Library/TeamTalk.NET/TeamTalkSrvBase.cs

Primary references to enum values.

Fix doxygen references in .NET documentation

---

Client/qtTeamTalk/channelstree.cpp

This only occurs when using mouse as input.
This fixes #1663.

Fix all stream types being enabled when all should be disabled

---

.github/workflows/windows.yml
Documentation/TeamTalk/TeamTalk5.dox
Documentation/TeamTalk/mainpage.md
Documentation/TeamTalk/userinterface.md
Documentation/TeamTalkSDK/TeamTalk.Java.dox
Documentation/TeamTalkSDK/TeamTalk.NET.dox
Documentation/TeamTalkSDK/TeamTalk.dox

Windows workflow is still failing due to Qt deployment failing.

Fix markdown reference errors in Doxygen v1.9.8

---

.github/workflows/windows.yml

Qt deploy cannot find OpenSSL libraries libcrypto.dll and libssl.dll

Exclude VS2019Release32 from Windows workflow

---

Documentation/TeamTalk/advanced.md

This PR simply fixes a typo I found in the advanced documentation.

[Docs]: Fix typo in advanced TeamTalk5 documentation.

---

ChangeLog.txt
Client/TeamTalkAndroid/build.gradle
Client/TeamTalkAndroid/src/main/AndroidManifest.xml
Client/TeamTalkAndroid/src/main/java/dk/bearware/backend/TeamTalkService.java

Android 14 with targetSdkVersion=34 and
android.content.pm.ServiceInfo.FLAG_STOP_WITH_TASK causes the following exception:
android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{91b6812 15893:dk.bearware.gui/u0a192} targetSDK=34 ...
at android.app.Service.startForeground(Service.java:775)
at dk.bearware.backend.TeamTalkService.displayNotification(TeamTalkService.java:402)

Change foreground type to include FOREGROUND_SERVICE_TYPE_MICROPHONE

---

CMakeLists.txt
Client/CMakeLists.txt
Client/TeamTalkClassic/CMakeLists.txt
Client/qtTeamTalk/CMakeLists.txt
Client/qtTeamTalk/qt/CMakeLists.txt
Client/ttserverlog/CMakeLists.txt
Library/TeamTalkJNI/CMakeLists.txt
Library/TeamTalkLib/CMakeLists.txt
Library/TeamTalkLib/build/CMakeLists.txt
Library/TeamTalkLib/build/ace/CMakeLists.txt
Library/TeamTalkLib/build/catch2/CMakeLists.txt
Library/TeamTalkLib/build/ffmpeg/CMakeLists.txt
Library/TeamTalkLib/build/libvpx/CMakeLists.txt
Library/TeamTalkLib/build/ogg/CMakeLists.txt
Library/TeamTalkLib/build/openssl/CMakeLists.txt
Library/TeamTalkLib/build/opus/CMakeLists.txt
Library/TeamTalkLib/build/opustools/CMakeLists.txt
Library/TeamTalkLib/build/portaudio/CMakeLists.txt
Library/TeamTalkLib/build/speex/CMakeLists.txt
Library/TeamTalkLib/build/speexdsp/CMakeLists.txt
Library/TeamTalkLib/build/tinyxml/CMakeLists.txt
Library/TeamTalkLib/build/webrtc/CMakeLists.txt
Library/TeamTalkLib/build/zlib/CMakeLists.txt
Server/TeamTalkServer/CMakeLists.txt

All supported platforms have CMake >= 3.1 anyway.

Fix CMake 3.5 deprecation warning

---

Library/TeamTalkJNI/test/dk/bearware/TeamTalkTestCase.java

For some reason the overflow message is not in the queue. This seems like a bug though.

Disable testMessageQueue due to unstability

---

Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java

At first this button should switch to the channels tab. Anyway, it
definitely should not kick user out of the server if some other tab is
selected.

Android client: navigate up button behaviour fix

---

Client/TeamTalkAndroid/src/main/java/dk/bearware/data/Permissions.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java

1) Implemented requests queue to prevent responses mess-up and some
dialogs loss.
2) When all media files (images, video and audio) access is not
granted in modern Android, other files (text or pdf documents for
instance) still can be read. Thus, files upload facility remains actual
in this case.

A couple of fixes for requesting permissions in the Android client

---

Client/TeamTalkAndroid/build.gradle
Client/TeamTalkAndroid/src/main/AndroidManifest.xml
Client/TeamTalkAndroid/src/main/java/dk/bearware/backend/TeamTalkService.java

… and bump to v5.15.2 build 128
This is a test version to see if users notice a difference when android.permission.FOREGROUND_SERVICE is no longer acquired.

Remove android.permission.FOREGROUND_SERVICE

---

Client/TeamTalkAndroid/src/main/java/dk/bearware/data/TTSWrapper.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/PreferencesActivity.java

TTSWrapper.getEngines() is a static method and 'tts' is null if TTSWrapper has never been instantiated.
MainWindow instantiates TTSWrapper but Settings does not.
This fixes #1895

Fix TTS crash in Settings when not connected

---

ChangeLog.txt
Client/TeamTalkAndroid/src/main/java/dk/bearware/data/TextMessageAdapter.java

This should fix #2229:
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131230864, class android.widget.ListView) with Adapter(class dk.bearware.data.TextMessageAdapter)]

Prevent TextMessageAdapter from modifying during list view update

---

Client/TeamTalkAndroid/src/main/AndroidManifest.xml
Client/TeamTalkAndroid/src/main/java/dk/bearware/backend/TeamTalkService.java

This effectively reverts #2226 since it breaks microphone functionality
when screen is locked.

Android client: foreground service restored

---

Client/qtTeamTalk/utilsound.cpp

This prevents the same sound from being played again and fixes #2220

Do not reuse QSoundEffect object for next sound event

---

ChangeLog.txt
Client/qtTeamTalk/useraccountsmodel.cpp
Client/qtTeamTalk/useraccountsmodel.h

This allows screenreaders to see if an item is checked without accessible text role in Qt6

Use Qt checkable flags in user rights model

---

Client/qtTeamTalk/mainwindow.cpp

I found it more clear to display dialog box when manually checking for update, even if settings_display_appupdate_dlg is set to false.

Display dialogbox for manual update check

---

ChangeLog.txt
Client/qtTeamTalk/userinfo.ui
Client/qtTeamTalk/userinfodlg.cpp

Maybe usage of readonly QLineEdit was wanted, but I didn't see the real advantage of it.
So, I just replaced it by static QLabel

Only use QLabel in User info dialog

---

Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/preferences.ui
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/settings.h

Following switch to QTableView, and Qt6 providing native accessibility for trees on MacOS, this option seams to be useless now.

Remove macOS TTS speak on list option

---

Client/qtTeamTalk/channelstree.cpp

If someone has any idea for channel operator and administrator, maybe we can also replace "channel operator" and "administrator" by emojis. This make channel item shorter

Replace some texts by emojis in channel list

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/utilui.cpp
Client/qtTeamTalk/utilui.h

- Only use one dialog to enter username and password on login error and channel share
- Add ability to show password on login error, channel share, channel password and channel operator password

Simplify several dialogs

---

Client/qtTeamTalk/serverlistdlg.cpp
Client/qtTeamTalk/serverlistdlg.h

When calling getSelectedHost() we get a HostEntryEx from the models and the HostEntryEx defaults to SERVERTYPE_LOCAL when a latest host is selected.

Alternative way for #2352

---

Client/qtTeamTalk/mainwindow.cpp

Some TTS config keys are no longer use and can be remove from config file

Remove unused config keys from config file at first version startup

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp

I thought it can be useful to have OS version available to debug sometimes

Use prettyProductName instead of productType on login

---

ChangeLog.txt
Client/qtTeamTalk/preferences.ui
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/settings.h
Client/qtTeamTalk/utilsound.cpp

Option enabled by default to follow behaviour introduced in 5.17
Fixed #2431

Option to use TeamTalk sound Output device for default sound event playback mode

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/settings.h
Client/qtTeamTalk/utilui.cpp

migrateSettings is call before language selection, if TT has never been started, migrateSettings define a lanauge, so SETTINGS_DISPLAY_LANGUAGE is always set and the language selection isn't trigger.
So, I changed the check to ask for language selection if it is the first startup and not only if SETTINGS_DISPLAY_LANGUAGE isn't present, and I add a check to ensure migrateSettings define a new language only if SETTINGS_DISPLAY_LANGUAGE is previously set.

Correctly ask for language selection at first start

---

Build/Makefile

iOS SDK 18.1 is unable to build ACE (clang crashes). Max iOS deployment target for armv7 is iOS 10 which is already quite old.

Remove support for armv7 and i386 on iOS

---

ChangeLog.txt
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java
Client/TeamTalkAndroid/src/main/res/values/strings.xml

Currently, as much as the select for move option is clicked, it selects the user, which results the app trys to move that user 20 times to the destination channel. But now, like windows clients, once clicking this option will select the user and change the title to deselect for move for that user, and clicking it again will deselect that user.

Android client. Fixed select for move option

---

Client/qtTeamTalk/utilsound.cpp
Library/TeamTalkLib/avstream/WebRTCPreprocess.cpp

When duplex mode is disabled (due to echo cancellation = off) then WebRTC preprocessor is still active in echo cancellation mode. WebRTC then tries to access an AudioFrame::output_samples which is no longer available.
In other words the WebRTC preprocessor is configured in a way that is incompatible with the sound device configuration. WebRTC can only echo cancel when sound devices are initialized with
TT_InitSoundDuplexDevices().

Fix crash issue when toggling echo cancellation off

---

ChangeLog.txt
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/ServerListActivity.java
Client/TeamTalkAndroid/src/main/res/layout-land/item_serverentry.xml
Client/TeamTalkAndroid/src/main/res/layout/item_serverentry.xml
Client/TeamTalkAndroid/src/main/res/menu/server_actions.xml
Client/TeamTalkAndroid/src/main/res/values/strings.xml

before, a remove button was existed beside all servers, and long pressing a server would edit that server. that way, screenreader users needed to swipe twice to reach the next server, so for example, to find 20th server, we needed to swipe 40 times, because there was a remove button beside every server. But now, exactly like the desktop qt client's host manager that was recoded in 5.17, I recoded android client's server list to make it use popup menus, modern, and much more cleaner and clear.
This fixes
https://github.com/BearWare/TeamTalk5/issues/2536

Android client. Recoded server list dialog

---

ChangeLog.txt
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/ServerEntryActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/ServerListActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/Utils.java

from now on, when exporting a tt file, doesn't matter for a single server or the server list, the remember last channel checkbox's value will also be saved on tt files as how as the user have set them and will be loaded when importing tt file, so users do not have to turn it on or off again for any server, their settings are restored as how as it was before.
this fixes https://github.com/BearWare/TeamTalk5/issues/2554

Android. remember last channel value saved on tt files

---

Client/qtTeamTalk/serverdlg.ui

Qt client called it "Latest Joined Channel".

Align "Last Joined Channel" with Android client

---

Client/qtTeamTalk/chattextlist.cpp
Client/qtTeamTalk/mainwindow.ui

* Avoid to use same accelerator key multiple times
* Remove accessible name and accessible description from ui file, already defined by cpp
* Use getFormattedSize for disk quota, same as plain text history

Hotfixes for new history list

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/settings.h
Client/qtTeamTalk/utilsound.cpp
Client/qtTeamTalk/utilui.cpp

Avoid to ask for default sound pack usage at every language change.
@bear101 The migratioon of SETTINGS_SOUNDS_PACK in utilui.cpp isn't apply, do you know why, I don't understand :(

Don't translate "Default" sound pack name

---

.github/workflows/ios.yml

Use dorny/paths-filter GitHub action to limit builds of iTeamTalk using 'xcodebuild' because the build time is 4 hours.
2025-04-20T07:10:56.2240450Z     /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -c ...
...
2025-04-20T11:19:00.9301740Z /Users/runner/work/TeamTalk5/TeamTalk5/Client/iTeamTalk/iTeamTalk/WebLoginViewController.swift:134:29: warning: 'UIAlertView' was deprecated in iOS 9.0: UIAlertView is deprecated. Use

Limit builds of iTeamTalk to source code modifications

---

Client/qtTeamTalk/chattextedit.cpp
Client/qtTeamTalk/chattextlist.cpp
Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/mainwindow.h

MOTD wasn't displayed if dialog box to display MOTD was enabled and chat control was configured as a list.
Also fix some missing spaces in updateServer() and joinedChannel()

Fix MOTD not displayed in chat list

---

Client/qtTeamTalk/mainwindow.cpp
Client/qtTeamTalk/preferencesdlg.cpp

Found! The saving of toast notification checkbox was incorrectly placed after ending of test block to check if TTS tab has been changed.
Fixed #2579

Fix toast notification saving if TTS tab wasn't be initialized

---

ChangeLog.txt
Client/qtTeamTalk/preferencesdlg.cpp
Client/qtTeamTalk/preferencesdlg.h

Requested by Persian translator because some users asked why some messages are keeped in English when a translation is apply

Ask to retranslate TTS Events and Status Messages on language change

---

Client/qtTeamTalk/main.cpp
Documentation/TeamTalk/advanced.md

Requested by @Nardol for automatic update detection, download and installation. Can probably be useful to others.
@bear101 I see a strange behaviour on Windows, version is print directly in the prompt, not on another line as it is habitually the case. Do you know a better way to handle info on Windows?

Add "-v" command line argument to retrieve TT version

---

ChangeLog.txt
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java
Client/TeamTalkAndroid/src/main/res/layout/activity_main.xml
Client/TeamTalkAndroid/src/main/res/values/strings.xml

So, I've replaced these buttons finally, and made them exactly act as the buttons, the text is not removed so sited users also can have an idea of what the sliders are for, and also inclooded content description for blind users.
When activating or deactivating the voice activation, exactly like the buttons did, the content description and the text's labels will be changed to reflect the new value and change, also the slider's value will be updated to reflect the value of the gain or voice activation, So there is no mismatch, every changes are being tested, and made sure there is no crash, no unexpected bug, and sliders are completely normally, kicked out the buttons. Now people can enjoy using these. I'm really happy now when looking at teamtalk's screen now, both the server list and main …

Android. Old 4 buttons has been replaced with 2 new brand nice seekbars

---

ChangeLog.txt
Client/qtTeamTalk/mainwindow.ui

Following addition of CTRL+Shift+C to copy message content, to avoid conflict bitween shortcuts

Use Ctrl+Shift+R to generate tt:// URL for current channel

---

ChangeLog.txt
Client/TeamTalkAndroid/src/main/java/dk/bearware/backend/TeamTalkService.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/data/Preferences.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/data/ServerEntry.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/PreferencesActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/ServerEntryActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/ServerListActivity.java
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/Utils.java
Client/TeamTalkAndroid/src/main/res/layout/activity_server_entry.xml
Client/TeamTalkAndroid/src/main/res/values/strings.xml
Client/TeamTalkAndroid/src/main/res/xml/pref_general.xml

As promiced before, i've added the ability to set status message for android client, and more surprise, is that I've desighned it like nickname, Which means you'll be able to set difrent status messages for each server seperatly if you want, and if you don't, your general status message will be used, exactly like nickname. Also, status messages for servers are stored on .tt files as well, so no worrys about losing them! enjoy!

Android client: Added the ability to set status messages.

---

Library/TeamTalkPy/TeamTalk5.py
Library/TeamTalkPy/test/teamtalk_test.py

UTF-8 array should only be split where characters are still valid.

Fix overlapping UTF-8 string in Python TextMessage

---

Client/qtTeamTalk/changestatusdlg.cpp
Client/qtTeamTalk/mainwindow.cpp

Following #2711, status message change was partially broken using "Change status" dialog

Fixed status message change

---

ChangeLog.txt
Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java
Client/TeamTalkAndroid/src/main/res/values/strings.xml
Client/TeamTalkAndroid/src/main/res/xml/pref_general.xml

So many screenreader users are annoyed by this fact that talking users are moved to the top of the list of users, because in a channel that has so many users and users are constantly opening and closing their microphones, the blind user will end up messaging, moving, kicking etc, taking action on a wrong user or they cannot do that because users are constantly moving up and down.
Added a new option, checked by default to not break current way for sited users, which if unchecked, users will no longer move up and down, which makes it stable for blind users. Sited users or whoever wants, they can check this box, and who don't wish, can uncheck it.

Android client. Added a new option to prevent talking users to be moved to the top of users list

---

ChangeLog.txt
Library/TeamTalkJNI/test/dk/bearware/TeamTalkTestCase.java
Library/TeamTalkLib/bin/ttsrv/ServerGuard.cpp
Library/TeamTalkLib/bin/ttsrv/ServerXML.cpp
Library/TeamTalkLib/bin/ttsrv/ServerXML.h

Resolves #2201 by implementing a mechanism to purge stale channel operator rights upon channel deletion.
A new public method, ServerXML::CleanupChannelOperators(int channelId), is introduced to iterate through users and remove operator privileges for a specific channel ID. The ServerGuard::OnChannelRemoved method has been updated to call this new function.

fix(Server): Prevent accidental operator inheritance on channel ID reuse

---

Client/TeamTalkAndroid/src/main/java/dk/bearware/backend/TeamTalkService.java

@bear101 when you were implementing login complete functions in ttservice, you touched this function and due to some incorrect checks, it was became broken, whitch i've now fixed it.
this fixes https://github.com/BearWare/TeamTalk5/issues/2753

Android. fixed client not joining the channel specifyed in server prop dialog

---

Client/qtTeamTalk/utilui.cpp

In the current setup, the notification stays on the screen for 3 ms. Orca doesn't have time to read it, so we get empty notifications.
By increasing the time to 0.5 s, Orca has time to read the notification.

fix time notification on linux

---

Library/TeamTalkLib/build/CMakeLists.txt
Library/TeamTalkLib/build/webrtc/CMakeLists.txt

On Windows it appears that WebRTC will only accept c:\webrtc

Make WEBRTC_FETCH_PATH configurable

---

ChangeLog.txt
Client/qtTeamTalk/CMakeLists.txt

Qt v6.9.2 is built for macOS 12

Bump qtTeamTalk CMAKE_OSX_DEPLOYMENT_TARGET to 12.0

---

Library/TeamTalkLib/teamtalk/User.h

User::GetMaxDataChunkSize() was assigned same value as User::GetMaxPayloadSize() causing no space for FIELDHEADER_PAYLOAD.

Fix desktop sharing OOM issue causing crash in TeamTalk server
